<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <!--Mismas configuraciones que el add-in para que la solucion las encuentre en todos los proyectos-->
    <PropertyGroup>
        <Configurations>Debug;Release;Debug R24;Release R24</Configurations>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
        <Optimize>false</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('Release'))">
        <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Doly.Core\Doly.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Datos\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
